# permissions to do viewer clustersets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterset-viewer-role
rules:
- apiGroups:
  - clustersets.mumo.co
  resources:
  - clustersets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clustersets.mumo.co
  resources:
  - clustersets/status
  verbs:
  - get
